version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: spdx
    versions:
    - "> 2.0.10"
  - dependency-name: oj
    versions:
    - 3.11.4
  - dependency-name: chartkick
    versions:
    - 4.0.0
    - 4.0.3
  - dependency-name: pg_query
    versions:
    - 2.0.1
    - 2.0.3
  - dependency-name: listen
    versions:
    - 3.5.1
  - dependency-name: pghero
    versions:
    - 2.7.4
    - 2.8.0
    - 2.8.1
  - dependency-name: counter_culture
    versions:
    - 2.8.0
  - dependency-name: sidekiq
    versions:
    - 6.2.0
  - dependency-name: ox
    versions:
    - 2.14.2
    - 2.14.3
  - dependency-name: pagy
    versions:
    - 3.11.0
    - 3.12.0
  - dependency-name: semantic_range
    versions:
    - 3.0.0
  - dependency-name: octicons_helper
    versions:
    - 12.0.0
    - 12.1.0
  - dependency-name: rails
    versions:
    - 6.1.2.1
    - 6.1.3
  - dependency-name: commonmarker
    versions:
    - 0.21.2
  - dependency-name: puma
    versions:
    - 5.2.1
  - dependency-name: bootsnap
    versions:
    - 1.7.0
    - 1.7.1
    - 1.7.2
